import type { ToolContext } from "@opencode-ai/plugin";
import * as fs from "node:fs/promises";
import * as path from "node:path";
import { 
  extractTracksFromRegistry, 
  readTrackPlan, 
  parsePlanProgress,
  Track,
  PlanProgress 
} from "../utils/parser";

export async function executeStatusCommand(input: { client: any, directory: string }, context: ToolContext): Promise<string> {
  const { client } = input;
  const directory = input.directory || context.directory;
  const registryPath = path.join(directory, "conductor", "tracks.md");
  const registryDir = path.join(directory, "conductor");

  try {
    const registryContent = await fs.readFile(registryPath, "utf-8");
    const tracks = extractTracksFromRegistry(registryContent);
    const trackDetails: Array<{ track: Track, progress: PlanProgress | null }> = [];

    let totalTasks = 0;
    let completedTasks = 0;
    const allBlockers: string[] = [];

    for (const track of tracks) {
      const planContent = await readTrackPlan(registryDir, track.link);
      const progress = planContent ? parsePlanProgress(planContent) : null;
      
      if (progress) {
        totalTasks += progress.totalTasks;
        completedTasks += progress.completedTasks;
        allBlockers.push(...progress.blockers);
      }
      
      trackDetails.push({ track, progress });
    }

    const overallPercentage = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;
    
    // 1. Toast Notification
    await client.tui.showToast({
      variant: "success",
      title: "Conductor Status",
      message: `Project Progress: ${overallPercentage}% (${completedTasks}/${totalTasks} tasks completed)`
    });

    // 2. Format detailed summary
    const summaryMarkdown = formatStatusSummary(trackDetails, overallPercentage, completedTasks, totalTasks, allBlockers);
    
    // 3. Append to prompt
    await client.tui.appendPrompt(summaryMarkdown);

    return `[CONDUCTOR] Status summary generated (${overallPercentage}%)`;

  } catch (error: any) {
    await client.tui.showToast({
      variant: "error",
      title: "Status Command Failed",
      message: error.message
    });
    return `[CONDUCTOR] Failed to generate status: ${error.message}`;
  }
}

function formatStatusSummary(
  details: Array<{ track: Track, progress: PlanProgress | null }>,
  overallPercentage: number,
  totalCompleted: number,
  totalTasks: number,
  blockers: string[]
): string {
  const now = new Date().toLocaleString();
  
  let md = `## Conductor Project Status Summary
**Timestamp:** \`${now}\`
**Overall Progress:** \`${overallPercentage}%\` (${totalCompleted}/${totalTasks} tasks)

---

### Track Breakdown
`;

  details.forEach(({ track, progress }) => {
    const percentage = progress && progress.totalTasks > 0 
      ? Math.round((progress.completedTasks / progress.totalTasks) * 100) 
      : 0;
    
    md += `\n#### **${track.description}**
- **Status:** \`${track.status.toUpperCase()}\`
- **Progress:** \`${percentage}%\` (${progress?.completedTasks || 0}/${progress?.totalTasks || 0} tasks)
`;

    if (progress) {
      if (progress.currentPhase) {
        md += `- **Current Phase:** ${progress.currentPhase}\n`;
      }
      if (progress.currentTask) {
        md += `- **Active Task:** ${progress.currentTask}\n`;
      } else if (progress.nextAction) {
        md += `- **Next Action:** ${progress.nextAction}\n`;
      }
      if (progress.blockers.length > 0) {
        md += `- **Blockers:** ${progress.blockers.join(", ")}\n`;
      }
    } else {
      md += `- _(plan.md not found)_\n`;
    }
  });

  if (blockers.length > 0) {
    md += `\n### 🚨 ALL BLOCKERS\n- ${blockers.join("\n- ")}\n`;
  }

  md += `\n---
Generated by Conductor. Run \`/conductor:status\` anytime to refresh this view.`;

  return md;
}
